name: terraform

on:
  workflow_dispatch:
     inputs : 
      region :
        description: "Enter your region : "
        required: true  
        type: string 

env:
  BUCKET: aman-batch-s3
  TFSTATE_FILE: terraform.tfstate
  aws_region: ${{ github.event.inputs.region }}

jobs:
  ec2-instance:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform hashicorp setup
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }}
          aws-region: ${{ env.aws_region }} 
      
      - name: terraform init
        run: |
          cd module
          terraform init 
      - name: terraform plan
        run: |
          cd module
          terraform plan
      - name: terraform apply
        run: |
          cd module 
          terraform apply -auto-approve